#!/bin/bash

msg() {
	echo ">> $*"
}

die() {
	msg "$*"
	exit 1
}

cat <<END >&2
any2ogg by AITap, 2011
Published under GPLv3 or later
END

if [ $# -eq 0 ]
then
	cat <<END
Usage: $0 <file.flac|file.ape|file.wv> [file ...]
 - splits selected files using CUE sheet (if detected) 
 - recodes them to OGG Vorbis
 - recursively self-calls on directory contents
 - is tag-friendly
END
	exit 0
fi

for p in shntool oggenc ffmpeg cueprint mac
do
	which $p &>/dev/null || die "$p not found on your system!"
done

for file in "$@"
do
	msg "Doing: $file"
	basename=$(basename "$file")

	if [ -d "$file" ]
	then
		msg "'$file' is a directory"
		file=$(readlink -e "$file")
		mkdir -p "$basename" || die "mkdir failed"
		cd "$basename"
		$0 "$file"/*
		cd ..
		continue
	elif [ -r "$file" ] && echo "$file" | egrep -qi "\.(flac|wv|ape)$"
	then
		for guess in "${file}.cue" "$(sed -r 's/\..{2,4}$/.cue/'<<<"$file")" # встроенным variable substitution - не вышло
		do
			if [ -r "$guess" -a "$guess" != "$file" ]
			then
				msg "Detected CUE: $guess"
				cue=$(date +/tmp/%s.cue)
				cat "$(readlink -e "$guess")" | \
				enconv > "$cue" && \
					break || msg "WARNING: failed to recode $guess"
			fi
		done
		if [ -z "$cue" ] && ffprobe -show_format "$1" 2>/dev/null | grep -q 'TAG:Cuesheet'
		then
			msg "Detected embedded CUE"
			ffprobe -show_format "$file" | \
			sed -n 'H;${g;s/.*TAG:Cuesheet=//;s/\nTAG:.*//;p}' | \
			enconv > "$tcue" || {
				msg "Failed to recode embedded CUE"
				rm -vf "$cue"
				unset cue
			}
		fi
	
		if [ -n "$cue" ]
		then
			file=$(readlink -e "$file")
			dir=$(awk '($2=="DATE"){Y=$3};($1=="TITLE"){$1="";T=gensub(/^ |["\r]/,"","g")};/TRACK/{printf "%4d - %s",Y,gensub(/[\/:]/,"_","g",T);exit}' "$cue")
			[ -z "$dir" ] && dir="$basename"
			mkdir -pv "$dir" && cd "$dir" || die "mkdir failed"

			msg "Splitting file"
			shnsplit -o 'cust ext=ogg oggenc -q7 -Q -o %f -' -m '?_/-:_'  -t "%n. %t" -f "$cue" "$file" || die "shnsplit failed"
			rm -vf "00. pregap.ogg"

			msg "Tagging files"
			cuetag "$cue" *.ogg

			msg "Cleaning up"
			rm -vf "$cue"

			continue
		else
			ffmpeg -loglevel warning -i "$file" -vn -aq 5 -acodec libvorbis "$(sed -r 's/\..{2,4}$/.ogg/'<<<${basename})" || die "ffmpeg failed"
		fi
	else
		msg "'$file' doesn't look like a suitable file, skipping"
		continue
	fi
done
