#!/bin/bash

cat << WELCOME
cue2flac by AITap, 2009
Published under GPLv3 or later
WELCOME

USAGE="Usage: $0 <source file> [CUE file]"

function die () {
    echo -e $1
    exit 1
}

[ "$DEBUG" ] && set -x
[ $# -eq 0 ] && die "$USAGE"
[ -z "$1" ] && die "Source file not defined!"

for prog in ffmpeg ffprobe cuetag cuebreakpoints shnsplit flac enconv lltag
do
	echo -n ">> Checking for $prog: "
	which $prog || die "$prog not found!"
done

if [ -n "$2" ]
then
	cue="$2"
else
	for guess in "$1.cue" "$(sed -e "s/\.[^.]*$/.cue/g" <<<$1)" # "${1/%@(.???|.????)/.cue}" не работает
	do
		if [ -r "$guess" -a "$guess" != "$1" ]
		then
			cue="$guess"
			echo ">> CUE detected: $guess"
			break
		fi
	done
	if [ -z "$cue" ] && ! ffprobe -show_format "$1" 2>/dev/null | grep -q 'TAG:Cuesheet'
	then
		die ">> CUE file is not defined and there is no embedded CUE!"
	fi
fi


# код для получения cue из файла:
# ffprobe -show_format | awk 'sub(/^TAG:Cuesheet=/,""){flag++}; /^TAG:/ && flag {exit}; flag{print}'
# или
# sed -n 'H;${g;s/.*TAG:Cuesheet=//;s/\nTAG:.*//;p}'
# спасибо komar с #linux@RusNet
# исходный вариант: | perl -ne '$flag=1 if s/^TAG:Cuesheet=//; exit if /^TAG:/; print if $flag'

if [ "$cue" ]
then
	echo ">> Recoding CUE for the current locale..."
	tempcue=$(date +%s.cue)
	enconv < "$cue" > $tempcue
else
	echo ">> Getting CUE from main file..."
	tempcue=$(date +%s.cue)
	ffprobe -show_format "$1" | sed -n 'H;${g;s/.*TAG:Cuesheet=//;s/\nTAG:.*//;p}' | enconv > $tempcue
fi

test -s "$tempcue" || die ">> Someting went wrong"


tempfile=$(date +%s.flac)

case "${1}" in
*.flac)
	echo ">> File is already encoded, symlinking to ${tempfile}"
	ln -s "$1" "$tempfile"
	;;
*)
	echo ">> Creating temporary full FLAC file: $tempfile"
	ffmpeg -i "$1" -acodec flac $tempfile || die ">> FFMPEG failed!"
	;;
esac

echo ">> Splitting full FLAC into tracks..."
cuebreakpoints "$tempcue" | shnsplit -o flac $tempfile || die ">> Splitting failed!"

echo ">> Removing temporary FLAC: $tempfile"
rm $tempfile 

echo ">> Setting tags for splitted tracks..."
cuetag "$tempcue" split-track*.flac || die ">> Tag setting failed!"

echo ">> Removing temporary CUE: $tempcue"
rm $tempcue

echo ">> Renaming split-track*.flac using tags..."
lltag --no-tagging --rename "%n. %t" --rename-slash - split-track*.flac || die ">> Renaming failed!"

echo ">> Everything is done."
