#!/bin/bash

if [ "$1" == "-s" ]
then
out=/dev/null
else
out=/dev/stderr #may be stdout
fi


cat << WELCOME > $out
FILEBIN.CA uploader script by AITap, 2009
Published under GPLv3 or later
WELCOME

if [ -z "$*" ]
then
cat << USAGE > /dev/stderr
Usage: $(basename $0) [-s] <file1> ... [filen]
Upload files to http://filebin.ca
-s: supress all output exept file URLs
USAGE
exit 1
fi


for file
do
if [ -r "$file" -o "$file" == "-" ]
then
echo -ne '\033[1m' > $out; du -h "${file}" > $out; echo -ne '\033[0m' > $out
echo -n 'Getting uploader identifier... ' > $out
ident=$(curl -s http://filebin.ca/ | grep UPLOAD_IDENTIFIER | sed 's/.*value="//;s/".*//') || exit 1
echo -n "uploading... " > $out
curl -# \
-A 'Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.15) Gecko/2009102815 Ubuntu/9.04 (jaunty) Firefox/3.0.15' \
-F file="@${file}" -F "UPLOAD_IDENTIFIER=$ident" -F "MAX_FILE_SIZE=582428800" \
http://filebin.ca/upload.php 2>$out 1>&1
fi
done
