#!/bin/bash


[ -z "$EMAIL" ] && EMAIL='krylov.r00t@gmail.com'
[ "$DEBUG" ] && set -x
[ -z "$LOG" ] && LOG=/dev/null

function upload () {
    echo -ne '\033[1m'; du -h "$1"; echo -ne '\033[0m'
    #echo -n "Please wait" > /dev/stderr
    #curl -# \
    curl \
    -F uploader_email="$EMAIL" \
    -F upload_file="@$1" \
    -F accept_tos=1 \
    http://www.filehosting.org/ > $LOG
    echo -ne '\033[1m'; if [ $? == 0 ]; then echo "$file: uploaded successfully, check inbox"; else echo "Something went wrong?"; fi; echo -ne '\033[0m'
}

function usage () {
cat > /dev/stderr << USAGE
Usage: $0 <filename1> .. <filename n>
Upload specified files to filehosting.org
EMAIL variable must be set in order to properly upload files.
USAGE
exit 1
}

cat > /dev/stderr << WELCOME
Filehosting.org uploader by AITap, 2009
WELCOME

[ -z "$*" ] && usage

for file
    do
    upload "$file"
done

echo "All files done." > /dev/stderr

