#!/bin/bash

cat <<WELCOME >/dev/stderr
qip-downloader by AITap, 2011
Published under GPLv3 or later
WELCOME

die() {
	echo
	exit 1
}

for url; do
echo -n "${url}"
url1="$(wget -qO- "${url}" | egrep -o '".*/get/[^ ]*"' | sed 's/^"//;s/"$//')" || die
echo -n " - ${url1}"
url2="$(wget -qO- "${url1}" | egrep -o '".*/download/.*"' | sed 's/^"//;s/"$//')" || die
echo " - ${url2}"
wget --trust-server-names "${url2}" || die
done
