#!/bin/bash

cat > /dev/stderr << WELCOME
RGHost uploader by AITap, 2009
Published under GPLv3 or later
WELCOME

if [ -z "$*" ]; then 
cat > /dev/stderr << MAN
Usage: $0 /path/to/file
Upload specified file to the http://rghost.ru/ site.
MAN
exit 1
fi

[ "$DEBUG" ] && set -x

for file
do
if [ "$file" != "-" ] && [ -r "$file" ]; then echo -ne '\033[1m' > /dev/stderr; du --apparent-size -h "$file"; echo -ne '\033[0m' > /dev/stderr; elif [ "$file" = "-" ]; then echo -e '\e[1mUploading from stdin\e[0m' >/dev/stderr; else continue; fi

echo -n "Getting authentification token... " > /dev/stderr
auth=`curl -s -b ~/.rghost.cookies -c ~/.rghost.cookies rghost.ru | grep 'upload_form' | cut -d '<' -f 5 | cut -d ' ' -f 4 | cut -d '"' -f 2` || exit 1

echo -n "getting server... " > /dev/stderr
server=`curl -s rghost.ru | grep -o 'http://[a-z]*.rghost.ru/files'` || exit 1

echo -n "uploading file..." > /dev/stderr
cat "$file" | curl -# \
-c ~/.rghost.cookies -b ~/.rghost.cookies \
-F authenticity_token="$auth" \
-F file="@-;filename=${NAME:-${file}}" \
$server | \
grep 'http://rghost.ru/private/[0-9]*/[0-9a-f]*' -o

done
